name: CI
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2

            - name: Composer Dependencies
              run: composer update --no-interaction --prefer-dist

            - name: Checks
              run: composer checks
