name: CI
on:
    push:
        branches: ['master']
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
            - uses: actions/cache@v2
              with:
                path: ~/.composer/cache/files
                key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            - name: Composer Dependencies
              run: composer update --no-interaction --prefer-dist

            - name: Checks
              run: composer checks
